//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.24 at 12:04:35 PM IST 
//


package com.omthacker.webservice_example;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetRestaurantResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetRestaurantResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RestaurantDetails" type="{http://omthacker.com/webservice-example}RestaurantDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRestaurantResponse", propOrder = {
    "restaurantDetails"
})
public class GetRestaurantResponse {

    @XmlElement(name = "RestaurantDetails", required = true)
    protected RestaurantDetails restaurantDetails;

    /**
     * Gets the value of the restaurantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RestaurantDetails }
     *     
     */
    public RestaurantDetails getRestaurantDetails() {
        return restaurantDetails;
    }

    /**
     * Sets the value of the restaurantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestaurantDetails }
     *     
     */
    public void setRestaurantDetails(RestaurantDetails value) {
        this.restaurantDetails = value;
    }

}
