//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.24 at 12:04:35 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://omthacker.com/webservice-example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.omthacker.webservice_example;
